CREATE TABLE NERD_ADDRESSES(
  NERD_ADDRESS_PK INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  LAST_UPDATE_DATE TIMESTAMP NOT NULL,
  EXPIRED_DATE TIMESTAMP NULL,

  ADDRESS_FK INT NOT NULL,
  NERD_FK INT NOT NULL,
  NERD_CONTACT_TYPE_FK INT NOT NULL,

  FOREIGN KEY (NERD_FK) REFERENCES NERDS(NERD_PK),
  FOREIGN KEY (ADDRESS_FK) REFERENCES ADDRESSES(ADDRESS_PK),
  FOREIGN KEY (NERD_CONTACT_TYPE_FK) REFERENCES NERD_CONTACT_TYPE(NERD_CONTACT_TYPE_PK)
)