CREATE TABLE NERD_DINNER_DESCRIPTIONS (
  NERD_DINNER_DESCRIPTION_PK INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NERD_DINNER_FK             INT           NOT NULL,
  LANGUAGE_CODE              NVARCHAR2(10)  NOT NULL,
  TITLE                      NVARCHAR2(255) NOT NULL,
  DESCRIPTION                NCLOB NOT NULL,
  FOREIGN KEY (NERD_DINNER_FK) REFERENCES NERD_DINNERS (NERD_DINNER_PK)
)