CREATE TABLE COUNTRIES (
  COUNTRY_PK   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  COUNTRY_CODE NVARCHAR2(10)       NOT NULL
);

CREATE TABLE COUNTRY_DESCRIPTION (
  COUNTRY_DESCRIPTION_PK INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  COUNTRY_FK             INT                NOT NULL,
  LANGUAGE_FK            INT                NOT NULL,
  COUNTRY_NAME           NVARCHAR2(255)      NOT NULL,

  FOREIGN KEY (COUNTRY_FK) REFERENCES COUNTRIES (COUNTRY_PK),
  FOREIGN KEY (LANGUAGE_FK) REFERENCES LANGUAGES (LANGUAGE_PK)
)