CREATE TABLE NERD_DESCRIPTIONS (
  NERD_DESCRIPTION_PK INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NERD_FK             INT                NOT NULL,
  LANGUAGE_FK         INT                NOT NULL,
  TITLE               NVARCHAR2(255)      NULL,
  COMPANY             NVARCHAR2(255)      NULL,
  BIOGRAPHY           NVARCHAR2(1000)      NULL,

  FOREIGN KEY (NERD_FK) REFERENCES NERDS (NERD_PK),
  FOREIGN KEY (LANGUAGE_FK) REFERENCES LANGUAGES (LANGUAGE_PK)
)