INSERT INTO NERD_CONTACT_TYPE (CONTACT_TYPE_CODE) VALUES ('Home');
INSERT INTO NERD_CONTACT_TYPE (CONTACT_TYPE_CODE) VALUES ('Work');

SET @englishPk = (SELECT LANGUAGE_PK
FROM LANGUAGES
WHERE LANGUAGE_CODE = 'en');
SET @spanishPk = (SELECT LANGUAGE_PK
FROM LANGUAGES
WHERE LANGUAGE_CODE = 'es');
SET @homeType = (SELECT TOP 1 NERD_CONTACT_TYPE_PK
FROM NERD_CONTACT_TYPE
WHERE CONTACT_TYPE_CODE = 'Home');
SET @workType = (SELECT TOP 1 NERD_CONTACT_TYPE_PK
FROM NERD_CONTACT_TYPE
WHERE CONTACT_TYPE_CODE = 'Work');

--en
INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LANGUAGE_FK, DESCRIPTION)
VALUES (@homeType, @englishPk, 'Home');
INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LANGUAGE_FK, DESCRIPTION)
VALUES (@workType, @englishPk, 'Work');

--es
INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LANGUAGE_FK, DESCRIPTION)
VALUES (@homeType, @spanishPk, 'Casa');
INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LANGUAGE_FK, DESCRIPTION)
VALUES (@workType, @spanishPk, 'Trabajo');