DECLARE englishPk INT;
spanishPk INT;
homeType INT;
workType INT;

BEGIN
  INSERT INTO NERD_CONTACT_TYPE (CONTACT_TYPE_CODE) VALUES ('Home');
  INSERT INTO NERD_CONTACT_TYPE (CONTACT_TYPE_CODE) VALUES ('Work');

  SELECT LANGUAGE_PK INTO englishPk FROM LANGUAGES WHERE LANGUAGE_CODE = 'en';
  SELECT LANGUAGE_PK INTO spanishPk FROM LANGUAGES WHERE LANGUAGE_CODE = 'es';
  SELECT NERD_CONTACT_TYPE_PK INTO homeType FROM NERD_CONTACT_TYPE WHERE CONTACT_TYPE_CODE = 'Home';
  SELECT NERD_CONTACT_TYPE_PK INTO workType FROM NERD_CONTACT_TYPE WHERE CONTACT_TYPE_CODE = 'Work';

--en
  INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LANGUAGE_FK, DESCRIPTION)
  VALUES (homeType, englishPk, 'Home');
  INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LANGUAGE_FK, DESCRIPTION)
  VALUES (workType, englishPk, 'Work');

  --es
  INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LANGUAGE_FK, DESCRIPTION)
  VALUES (homeType, spanishPk, 'Casa');
  INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LANGUAGE_FK, DESCRIPTION)
  VALUES (workType, spanishPk, 'Trabajo');
END;