CREATE TABLE ADDRESSES(
  ADDRESS_PK INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  STREET_LINE1 NVARCHAR2(255) NOT NULL,
  STREET_LINE2 NVARCHAR2(255) NOT NULL,
  CITY NVARCHAR2(255) NOT NULL,
  STATE CHAR(2) NOT NULL,
  ZIP NVARCHAR2(10) NOT NULL,
  TIME_ZONE_OFFSET_MINUTES INT NOT NULL
)