CREATE TABLE NERD_CONTACT_TYPE (
  NERD_CONTACT_TYPE_PK INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  CONTACT_TYPE_CODE    NVARCHAR2(255)      NOT NULL
);

CREATE TABLE NERD_CONTACT_TYPE_DESCRIPTIONS (
  NERD_CONTACT_TYPE_DESCRIPTION_PK INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NERD_CONTACT_TYPE_FK             INT                NOT NULL,
  LANGUAGE_FK                      INT                NOT NULL,
  DESCRIPTION                      NVARCHAR2(255)      NOT NULL,

  FOREIGN KEY (NERD_CONTACT_TYPE_FK) REFERENCES NERD_CONTACT_TYPE (NERD_CONTACT_TYPE_PK),
  FOREIGN KEY (LANGUAGE_FK) REFERENCES LANGUAGES (LANGUAGE_PK)
)
