CREATE TABLE NERDS (
  NERD_PK        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  FIRST_NAME     NVARCHAR2(255)      NOT NULL,
  LAST_NAME      NVARCHAR2(255)      NOT NULL,
  USER_NAME      NVARCHAR2(255)      NOT NULL UNIQUE,
  PASSWORD       NVARCHAR2(255)      NOT NULL,
  PASSWORD_RESET NVARCHAR2(255)      NULL,
  TITLE          NVARCHAR2(255)      NULL,
  COMPANY        NVARCHAR2(255)      NULL,
  BIOGRAPHY      NVARCHAR2(1000)      NULL,
  AVATAR         NVARCHAR2(255)      NOT NULL
)