CREATE TABLE NERD_DINNER_RESERVATIONS(
  NERD_DINNER_RESERVATION_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  NERD_DINNER_FK INT NOT NULL,
  NERD_FK INT NOT NULL,
  RESERVATION_DATE TIMESTAMP NOT NULL,
  CANCELLATION_DATE TIMESTAMP NULL,
  FOREIGN KEY (NERD_DINNER_FK) REFERENCES NERD_DINNERS(NERD_DINNER_PK),
  FOREIGN KEY (NERD_FK) REFERENCES NERDS(NERD_PK)

)