CREATE TABLE COUNTRIES (
  COUNTRY_PK   INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  COUNTRY_CODE NVARCHAR(10)       NOT NULL,
);

CREATE TABLE COUNTRY_DESCRIPTION (
  COUNTRY_DESCRIPTION_PK INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  COUNTRY_FK             INT                NOT NULL,
  LANGUAGE_FK            INT                NOT NULL,
  COUNTRY_NAME           NVARCHAR(255)      NOT NULL,

  FOREIGN KEY (COUNTRY_FK) REFERENCES COUNTRIES (COUNTRY_PK),
  FOREIGN KEY (LANGUAGE_FK) REFERENCES LANGUAGES (LANGUAGE_PK)
)