CREATE TABLE NERD_CONTACT_TYPE (
  NERD_CONTACT_TYPE_PK INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  CONTACT_TYPE_CODE    NVARCHAR(255)      NOT NULL
);

CREATE TABLE NERD_CONTACT_TYPE_DESCRIPTIONS (
  NERD_CONTACT_TYPE_DESCRIPTION_PK INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NERD_CONTACT_TYPE_FK             INT                NOT NULL,
  LANGUAGE_FK                      INT                NOT NULL,
  DESCRIPTION                      NVARCHAR(255)      NOT NULL,

  FOREIGN KEY (NERD_CONTACT_TYPE_FK) REFERENCES NERD_CONTACT_TYPE (NERD_CONTACT_TYPE_PK),
  FOREIGN KEY (LANGUAGE_FK) REFERENCES LANGUAGES (LANGUAGE_PK)
)
