INSERT INTO NERD_CONTACT_TYPE (CONTACT_TYPE_CODE) VALUES ('Home');
INSERT INTO NERD_CONTACT_TYPE (CONTACT_TYPE_CODE) VALUES ('Work');

--en-US
INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LOCALE_FK, DESCRIPTION)
VALUES (
  (SELECT TOP 1 NERD_CONTACT_TYPE_PK
   FROM NERD_CONTACT_TYPE
   WHERE CONTACT_TYPE_CODE = 'Home'),
  (SELECT TOP 1 LOCALE_PK
   FROM LOCALES
   WHERE LOCALE_ID = 'en_US'),
  'Home'
);

INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LOCALE_FK, DESCRIPTION)
VALUES (
  (SELECT TOP 1 NERD_CONTACT_TYPE_PK
   FROM NERD_CONTACT_TYPE
   WHERE CONTACT_TYPE_CODE = 'Work'),
  (SELECT TOP 1 LOCALE_PK
   FROM LOCALES
   WHERE LOCALE_ID = 'en_US'),
  'Work'
);

--en-GB
INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LOCALE_FK, DESCRIPTION)
VALUES (
  (SELECT TOP 1 NERD_CONTACT_TYPE_PK
   FROM NERD_CONTACT_TYPE
   WHERE CONTACT_TYPE_CODE = 'Home'),
  (SELECT TOP 1 LOCALE_PK
   FROM LOCALES
   WHERE LOCALE_ID = 'en_GB'),
  'Home'
);

INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LOCALE_FK, DESCRIPTION)
VALUES (
  (SELECT TOP 1 NERD_CONTACT_TYPE_PK
   FROM NERD_CONTACT_TYPE
   WHERE CONTACT_TYPE_CODE = 'Work'),
  (SELECT TOP 1 LOCALE_PK
   FROM LOCALES
   WHERE LOCALE_ID = 'en_GB'),
  'Work'
);

--es-ES
INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LOCALE_FK, DESCRIPTION)
VALUES (
  (SELECT TOP 1 NERD_CONTACT_TYPE_PK
   FROM NERD_CONTACT_TYPE
   WHERE CONTACT_TYPE_CODE = 'Home'),
  (SELECT TOP 1 LOCALE_PK
   FROM LOCALES
   WHERE LOCALE_ID = 'es_ES'),
  'Casa'
);

INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LOCALE_FK, DESCRIPTION)
VALUES (
  (SELECT TOP 1 NERD_CONTACT_TYPE_PK
   FROM NERD_CONTACT_TYPE
   WHERE CONTACT_TYPE_CODE = 'Work'),
  (SELECT TOP 1 LOCALE_PK
   FROM LOCALES
   WHERE LOCALE_ID = 'es_ES'),
  'Trabajo'
);

--es-MX
INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LOCALE_FK, DESCRIPTION)
VALUES (
  (SELECT TOP 1 NERD_CONTACT_TYPE_PK
   FROM NERD_CONTACT_TYPE
   WHERE CONTACT_TYPE_CODE = 'Home'),
  (SELECT TOP 1 LOCALE_PK
   FROM LOCALES
   WHERE LOCALE_ID = 'es_MX'),
  'Casa'
);

INSERT INTO NERD_CONTACT_TYPE_DESCRIPTIONS (NERD_CONTACT_TYPE_FK, LOCALE_FK, DESCRIPTION)
VALUES (
  (SELECT TOP 1 NERD_CONTACT_TYPE_PK
   FROM NERD_CONTACT_TYPE
   WHERE CONTACT_TYPE_CODE = 'Work'),
  (SELECT TOP 1 LOCALE_PK
   FROM LOCALES
   WHERE LOCALE_ID = 'es_MX'),
  'Trabajo'
);