CREATE TABLE NERDS(
  NERD_PK INT AUTO_INCREMENT NOT NULL PRIMARY KEY ,
  FIRST_NAME NVARCHAR(255) NOT NULL,
  LAST_NAME NVARCHAR(255) NOT NULL,
  USER_NAME NVARCHAR(255) NOT NULL UNIQUE,
  PASSWORD NVARCHAR(255) NOT NULL,
)