CREATE TABLE NERD_DESCRIPTIONS (
  NERD_DESCRIPTION_PK INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  NERD_FK             INT                NOT NULL,
  LANGUAGE_FK         INT                NOT NULL,
  TITLE               NVARCHAR(255)      NULL,
  COMPANY             NVARCHAR(255)      NULL,
  BIOGRAPHY           NVARCHAR(MAX)      NULL,

  FOREIGN KEY (NERD_FK) REFERENCES NERDS (NERD_PK),
  FOREIGN KEY (LANGUAGE_FK) REFERENCES LANGUAGES (LANGUAGE_PK)
)