CREATE TABLE NERD_DINNERS(
  NERD_DINNER_PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  TITLE NVARCHAR(255) NOT NULL,
  DESCRIPTION NVARCHAR(MAX) NOT NULL,
  DINNER_DATE TIMESTAMP,
  ADDRESS_FK INT NOT NULL,
  MAXIMUM_ATTENDANCE INT NOT NULL,
  TYPE NVARCHAR(255) NOT NULL,
  CREATOR_NERD_FK INT NOT NULL,
  FOREIGN KEY (ADDRESS_FK) REFERENCES ADDRESSES(ADDRESS_PK),
  FOREIGN KEY (CREATOR_NERD_FK) REFERENCES NERDS(NERD_PK)
)