CREATE TABLE ADDRESSES(
  ADDRESS_PK INT AUTO_INCREMENT PRIMARY KEY ,
  STREET_LINE1 NVARCHAR(255) NOT NULL,
  STREET_LINE2 NVARCHAR(255) NOT NULL,
  CITY NVARCHAR(255) NOT NULL,
  STATE CHAR(2) NOT NULL,
  ZIP NVARCHAR(10) NOT NULL,
  TIME_ZONE_OFFSET_MINUTES INT NOT NULL
)