CREATE TABLE NERD_DINNER_DESCRIPTIONS (
  NERD_DINNER_DESCRIPTION_PK INT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NERD_DINNER_FK             INT           NOT NULL,
  LANGUAGE_CODE              NVARCHAR(10)  NOT NULL,
  TITLE                      NVARCHAR(255) NOT NULL,
  DESCRIPTION                NVARCHAR(MAX) NOT NULL,

  FOREIGN KEY (NERD_DINNER_FK) REFERENCES NERD_DINNERS (NERD_DINNER_PK)
)